## improved ansible playbook for the compute nodes only
---
- name: Install and configure Slurm compute nodes
  hosts: compute
  become: true
  gather_facts: true

  vars:
    slurm_user: "slurm"
    slurm_log_dir: "/var/log/slurm"
    slurm_spool_dir: "/var/spool/slurmd"
    cgroup_conf_src: "templates/cgroup.conf"
    slurm_conf_src: "templates/slurm.conf"
    munge_key_dest: "/etc/munge/munge.key"
    munge_key_src: "/etc/ansible/artifacts/headnode/munge.key"
    controller_host: "headnode"   # must match your [controller] inventory alias

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure prerequisites for time sync (optional but recommended)
      ansible.builtin.package:
        name: chrony
        state: present

    - name: Check munge.key source exists on controller
      ansible.builtin.stat:
        path: "{{ munge_key_src }}"
      register: munge_src_stat
      delegate_to: "{{ controller_host }}"
      run_once: true

    - name: Fail if munge.key source missing
      ansible.builtin.fail:
        msg: "munge.key source not found at {{ munge_key_src }} on {{ controller_host }}. Fetch it first."
      when: not munge_src_stat.stat.exists
      run_once: true

  tasks:
    - name: Install compute packages
      ansible.builtin.apt:
        name:
          - slurmd
          - slurm-client
          - munge
          - libmunge2
        state: present

    - name: Ensure slurm group with controller GID
      ansible.builtin.group:
        name: "{{ slurm_user }}"
        gid: "{{ slurm_gid }}"
        state: present

    - name: Ensure slurm user with controller UID/GID
      ansible.builtin.user:
        name: "{{ slurm_user }}"
        uid: "{{ slurm_uid }}"
        group: "{{ slurm_user }}"
        shell: "{{ slurm_shell_controller }}"
        system: true
        state: present

    - name: Ensure log directory exists
      ansible.builtin.file:
        path: "{{ slurm_log_dir }}"
        state: directory
        owner: "{{ slurm_user }}"
        group: "{{ slurm_user }}"
        mode: "0755"

    - name: Ensure slurmd spool directory exists
      ansible.builtin.file:
        path: "{{ slurm_spool_dir }}"
        state: directory
        owner: "{{ slurm_user }}"
        group: "{{ slurm_user }}"
        mode: "0700"

    - name: Distribute munge key from controller (fetch then copy)
      ansible.builtin.fetch:
        src: "{{ munge_key_src }}"
        dest: "/tmp/munge.key.{{ controller_host }}"
        flat: true
      delegate_to: "{{ controller_host }}"
      run_once: true

    - name: Copy munge key to compute node
      ansible.builtin.copy:
        src: "/tmp/munge.key.{{ controller_host }}"
        dest: "{{ munge_key_dest }}"
        owner: munge
        group: munge
        mode: "0400"
      notify: Restart munge

    - name: Deploy cgroup.conf (v2-friendly minimal)
      ansible.builtin.template:
        src: "{{ cgroup_conf_src }}"
        dest: /etc/slurm/cgroup.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart slurmd

    - name: Deploy slurm.conf
      ansible.builtin.template:
        src: "{{ slurm_conf_src }}"
        dest: /etc/slurm/slurm.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart slurmd

    - name: Enable and start munge
      ansible.builtin.service:
        name: munge
        state: started
        enabled: true

    - name: Wait for munged socket to be ready
      ansible.builtin.wait_for:
        path: /var/run/munge/munge.socket.2
        state: present
        timeout: 30

    - name: Enable and start slurmd
      ansible.builtin.service:
        name: slurmd
        state: started
        enabled: true

  handlers:
    - name: Restart munge
      ansible.builtin.service:
        name: munge
        state: restarted

    - name: Restart slurmd
      ansible.builtin.service:
        name: slurmd
        state: restarted
